"""expand lead searchjob and add audit models

Revision ID: 6d700b6863f3
Revises:
Create Date: 2026-04-28 12:38:10.424302

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d700b6863f3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("normalized_company_name", sa.String(length=255), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=120), nullable=True),
        sa.Column("owner_name", sa.String(length=255), nullable=True),
        sa.Column("legal_form", sa.String(length=80), nullable=True),
        sa.Column("place_id", sa.String(length=255), nullable=True),
        sa.Column("google_place_id", sa.String(length=255), nullable=True),
        sa.Column("google_maps_url", sa.String(length=500), nullable=True),
        sa.Column("google_rating", sa.Float(), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=True),
        sa.Column("categories", sa.String(length=500), nullable=True),
        sa.Column("raw_place_json", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("source_query", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("score_reasons", sa.Text(), nullable=False),
        sa.Column("site_title", sa.String(length=255), nullable=True),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.Column("has_h1", sa.Boolean(), nullable=False),
        sa.Column("has_cta", sa.Boolean(), nullable=False),
        sa.Column("mobile_signals", sa.Boolean(), nullable=False),
        sa.Column("has_contact_info", sa.Boolean(), nullable=False),
        sa.Column("page_load_ms", sa.Integer(), nullable=True),
        sa.Column("impressum_found", sa.Boolean(), nullable=False),
        sa.Column("audit_notes", sa.Text(), nullable=False),
        sa.Column("parser_notes", sa.Text(), nullable=False),
        sa.Column("checked_pages", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_leads_city"), ["city"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_leads_company_name"), ["company_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_leads_domain"), ["domain"], unique=False)
        batch_op.create_index(batch_op.f("ix_leads_email"), ["email"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_leads_google_place_id"), ["google_place_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_leads_industry"), ["industry"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_leads_normalized_company_name"),
            ["normalized_company_name"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_leads_phone"), ["phone"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_leads_place_id"), ["place_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_leads_source_query"), ["source_query"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_leads_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_leads_website"), ["website"], unique=False)

    op.create_table(
        "search_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("keyword", sa.String(length=200), nullable=False),
        sa.Column("cities", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("raw_results_count", sa.Integer(), nullable=False),
        sa.Column("new_leads_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("total_processed", sa.Integer(), nullable=False),
        sa.Column("filtered_out", sa.Integer(), nullable=False),
        sa.Column("total_found_raw", sa.Integer(), nullable=False),
        sa.Column("total_created", sa.Integer(), nullable=False),
        sa.Column("duplicates_skipped", sa.Integer(), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.Column("current_city", sa.String(length=120), nullable=True),
        sa.Column("current_query", sa.String(length=255), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("log_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("score_overall", sa.Float(), nullable=True),
        sa.Column("score_performance", sa.Float(), nullable=True),
        sa.Column("score_accessibility", sa.Float(), nullable=True),
        sa.Column("score_best_practices", sa.Float(), nullable=True),
        sa.Column("score_seo", sa.Float(), nullable=True),
        sa.Column("score_content", sa.Float(), nullable=True),
        sa.Column("score_trust", sa.Float(), nullable=True),
        sa.Column("cwv_lcp_ms", sa.Integer(), nullable=True),
        sa.Column("cwv_inp_ms", sa.Integer(), nullable=True),
        sa.Column("cwv_cls", sa.Float(), nullable=True),
        sa.Column("cwv_fcp_ms", sa.Integer(), nullable=True),
        sa.Column("cwv_ttfb_ms", sa.Integer(), nullable=True),
        sa.Column("seo_title", sa.String(length=255), nullable=True),
        sa.Column("seo_meta_description", sa.Text(), nullable=True),
        sa.Column("seo_h1_count", sa.Integer(), nullable=True),
        sa.Column("seo_h2_count", sa.Integer(), nullable=True),
        sa.Column("seo_word_count", sa.Integer(), nullable=True),
        sa.Column("seo_canonical_url", sa.String(length=500), nullable=True),
        sa.Column("seo_noindex", sa.Boolean(), nullable=True),
        sa.Column("seo_robots_txt_found", sa.Boolean(), nullable=True),
        sa.Column("seo_sitemap_found", sa.Boolean(), nullable=True),
        sa.Column("trust_https", sa.Boolean(), nullable=True),
        sa.Column("trust_impressum_found", sa.Boolean(), nullable=True),
        sa.Column("trust_privacy_found", sa.Boolean(), nullable=True),
        sa.Column("trust_contact_found", sa.Boolean(), nullable=True),
        sa.Column("checked_url", sa.String(length=500), nullable=True),
        sa.Column("redirected_url", sa.String(length=500), nullable=True),
        sa.Column("page_language", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("raw_audit_json", sa.JSON(), nullable=True),
        sa.Column("raw_lighthouse_json", sa.JSON(), nullable=True),
        sa.Column("raw_pagespeed_json", sa.JSON(), nullable=True),
        sa.Column("meta_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_results_lead_id"), ["lead_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_results_status"), ["status"], unique=False
        )

    op.create_table(
        "audit_issues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("audit_result_id", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("element", sa.String(length=255), nullable=True),
        sa.Column("selector", sa.String(length=255), nullable=True),
        sa.Column("page_url", sa.String(length=500), nullable=True),
        sa.Column("score_impact", sa.Float(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("is_blocking", sa.Boolean(), nullable=False),
        sa.Column("raw_issue_json", sa.JSON(), nullable=True),
        sa.Column("meta_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_result_id"],
            ["audit_results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_issues", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_issues_audit_result_id"),
            ["audit_result_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_audit_issues_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_issues_code"), ["code"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_issues_severity"), ["severity"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_issues_severity"))
        batch_op.drop_index(batch_op.f("ix_audit_issues_code"))
        batch_op.drop_index(batch_op.f("ix_audit_issues_category"))
        batch_op.drop_index(batch_op.f("ix_audit_issues_audit_result_id"))

    op.drop_table("audit_issues")
    with op.batch_alter_table("audit_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_results_status"))
        batch_op.drop_index(batch_op.f("ix_audit_results_lead_id"))

    op.drop_table("audit_results")
    op.drop_table("search_jobs")
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leads_website"))
        batch_op.drop_index(batch_op.f("ix_leads_status"))
        batch_op.drop_index(batch_op.f("ix_leads_source_query"))
        batch_op.drop_index(batch_op.f("ix_leads_place_id"))
        batch_op.drop_index(batch_op.f("ix_leads_phone"))
        batch_op.drop_index(batch_op.f("ix_leads_normalized_company_name"))
        batch_op.drop_index(batch_op.f("ix_leads_industry"))
        batch_op.drop_index(batch_op.f("ix_leads_google_place_id"))
        batch_op.drop_index(batch_op.f("ix_leads_email"))
        batch_op.drop_index(batch_op.f("ix_leads_domain"))
        batch_op.drop_index(batch_op.f("ix_leads_company_name"))
        batch_op.drop_index(batch_op.f("ix_leads_city"))

    op.drop_table("leads")
    # ### end Alembic commands ###
